package br.univali.geometricstransformations;

import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author biankatpas
 */
public class GeometricTransformations extends javax.swing.JFrame
{

    /**
     * Creates new form GeometricTransformations
     */
    public GeometricTransformations()
    {
        initComponents();
        points = new ArrayList<>();
        t = new Transformation();
        br = new Bresenham();

        /*points.add(new Point(20, 40));
        points.add(new Point(40, 40));
        points.add(new Point(30, 60));*/
        
        points.add(new Point(180, 120));
        points.add(new Point(180, 56));
        points.add(new Point(259, 56));
        points.add(new Point(259, 120));

        br.add(points);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btScale = new javax.swing.JButton();
        btRotation = new javax.swing.JButton();
        btTranslation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btScale.setText("Scale");
        btScale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btScaleActionPerformed(evt);
            }
        });

        btRotation.setText("Rotation");
        btRotation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btRotationActionPerformed(evt);
            }
        });

        btTranslation.setText("Translation");
        btTranslation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btTranslationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btTranslation, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(btRotation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btScale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btScale, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRotation)
                .addGap(18, 18, 18)
                .addComponent(btTranslation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btRotation, btScale, btTranslation});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRotationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btRotationActionPerformed
    {//GEN-HEADEREND:event_btRotationActionPerformed
        int ang;
        do
        {
            ang = Integer.parseInt(JOptionPane.showInputDialog(null, "Informe o Ângulo(0-360): "));
        } while (ang < 0 || ang > 360);
        points = t.rotation(ang, points);
        draw(points);
        
    }//GEN-LAST:event_btRotationActionPerformed

    private void btScaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btScaleActionPerformed
    {//GEN-HEADEREND:event_btScaleActionPerformed
        int x = Integer.parseInt(JOptionPane.showInputDialog(null, "Informe X: "));
        int y = Integer.parseInt(JOptionPane.showInputDialog(null, "Informe Y:"));
        points = t.scale(new Point(x, y), points);
        draw(points);
    }//GEN-LAST:event_btScaleActionPerformed

    private void btTranslationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btTranslationActionPerformed
    {//GEN-HEADEREND:event_btTranslationActionPerformed
        int val = Integer.parseInt(JOptionPane.showInputDialog(null, "Informe: "));
        Point pQtd = new Point(val, val);
        points = t.translation(pQtd, points);
        draw(points);
    }//GEN-LAST:event_btTranslationActionPerformed

       
    public void draw(ArrayList<Point> pontos)
    {
        br.add(pontos);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GeometricTransformations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GeometricTransformations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GeometricTransformations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GeometricTransformations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GeometricTransformations().setVisible(true);

            }
        });
    }
    
    private Transformation t;
    private ArrayList<Point> points;
    private Bresenham br;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRotation;
    private javax.swing.JButton btScale;
    private javax.swing.JButton btTranslation;
    // End of variables declaration//GEN-END:variables
}
